### PR TITLE
[OpenCV.js] Update OpenCV.js

### LINKED ISSUE #1324: [example] Upgrade OpenCV.js for Chromium 84.

### PR DESCRIPTION
**Pull request by akineeic**
Fixed #1324

### CODE REVIEW

**Comment by akineeic** [comment]
Update OpenCV.js binary, which is built with emscripten 1.39.16 and opencv 4.3.0. @ibelem @BruceDai  PTAL, thanks.

**Comment by akineeic** [comment]
I'll test the example running with OpenCV.js and report the result.

**Comment by ibelem** [comment]
Thanks @akineeic please also test Web AI workload and https://huningxin.github.io/opencv.js/perf/perf_imgproc/

**Comment by akineeic** [comment]
> Thanks @akineeic please also test Web AI workload and https://huningxin.github.io/opencv.js/perf/perf_imgproc/ with R84 and higher builds.

I used emscripten 1.39.15 to build OpenCV.js since 1.39.16 will cause initalize issue. And the updated binary is able to run the example, Web AI workload and the threshold testing using OpenCV.js in chrome R84.

**Comment by ibelem** [comment]
Thanks @akineeic , merge this PR. also @BruceDai

**Comment by BruceDai** [comment]
@ibelem Done.

**Pull request merged**
