### PR TITLE
 [example] Support to switch preference options for example

### LINKED ISSUE #196: [example] Support to switch preference options for example.
Currently we use url parameter prefer=fast or prefer=sustained to switch BNNS or MPS backend, and the test html page would relaunch.

### PR DESCRIPTION
**Pull request by Wenzhao-Xiang**
Fix #196

### CODE REVIEW

**Comment by Wenzhao-Xiang** [comment]
The code structure in https://github.com/intel/webml-polyfill/issues/196#issuecomment-440882937 still have some problems. And now, all the example have been code refactoring.
For the example of image_classification_tflite, the model constructor is below:

**ImageClassificationModel.js**
```js
class ImageClassificationModel {
  constructor(kwargs) {
    this._tfModel = kwargs.tfModel;
    this._model = null;
    this._compilation;
    this._execution;
    this._tensorIds = [];
    this._operandIndex = 0;
    this._options = {
      softmax: kwargs.softmax,
    };
    this._backend = kwargs.backend;
    this._prefer = kwargs.prefer;
    if (this._backend === 'WebML') {
      if (nnNative === null) {
        throw Error('Fails to initialize neural network context');
      }
      this._nn = nnNative;
    } else if (this._backend === 'WASM' || this._backend === 'WebGL2') {
      this._nn = nnPolyfill;
    }
  }

  async createCompiledModel() {
    let options = {};
    if (this._backend === 'WebGL2') {
      options.useWebGL2 = true;
    }
    this._model = await this._nn.createModel(options);

    this._addTensorOperands();
    this._addOpsAndParams();
    this._addInputsOutputs()

    await this._model.finish();
    this._compilation = await this._model.createCompilation();
    this._compilation.setPreference(getPreferCode(this._backend, this._prefer));
    await this._compilation.finish();
    this._execution = await this._compilation.createExecution();
  }
```
Use an object `kwargs` to pass all the arguments:
```js
let kwargs = {
      tfModel: this.tfModel,
      backend: backend,
      prefer: prefer,
      softmax: this.postOptions.softmax || false,
    };
```
And prefer code is getting with `getPreferCode(this._backend, this._prefer)`, witch is implementing as following:

**./util/base.js**
```js
function getPreferCode(backend, prefer) {
  let nn = navigator.ml.getNeuralNetworkContext();
  let preferCode = nn.PREFER_FAST_SINGLE_ANSWER;
  if (getOS() === 'Mac OS' && backend === 'WebML') {
    if (prefer === 'sustained') {
      preferCode = nn.PREFER_SUSTAINED_SPEED;
    } else if (prefer === 'fast') {
      preferCode = nn.PREFER_FAST_SINGLE_ANSWER;
    }
  }
  return preferCode;
}
```
And now almost all the html elements jusr exist in **main.js/camera.js**.

**Comment by Wenzhao-Xiang** [comment]
Please go to https://wenzhao-xiang.github.io/intel/webml-polyfill/  for test.

**Comment by pinzhenx** [comment]
LGTM. Thanks for your great job.

**Comment by ibelem** [comment]
The "Failed to setup BNNS backend." is a general exception, we'd better to have "Not support BNNS backend" for Mobilenet when trying to switch to BNNS. Anyway OK to merge it.

**Pull request merged**
