### PR TITLE
change mocha css

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by huningxin** [comment]
I found the original url of mocha.css is unstable in my environment. Propose to change one. @BruceDai , PTAL. Thanks!

**Comment by BruceDai** [comment]
LGTM, thanks
@ibelem  Please help to merge this PR, thanks

**Comment by ibelem** [comment]
I prefer to embed all CSS file to html header if no extra fonts requirement instead of changing CDN urls due to our different network environment e.g. https://github.com/intel/webml-polyfill/pull/383

**Comment by huningxin** [comment]
> I prefer to embed all CSS file to html header if no extra fonts requirement instead of changing CDN urls due to our different network environment e.g. #383

Sounds good. As multiple html files use this, perhaps they can share one CSS file.

**Comment by huningxin** [comment]
close due to https://github.com/intel/webml-polyfill/pull/529

**Pull request closed without merging**
