### PR TITLE
[doc][test] Support a new preference code 'ULTRA_LOW_POWER' for testing GNA plugin.

### PR DESCRIPTION
**Pull request by BruceDai**
@huningxin @fujunwei @ibelem PTAL, thanks

So we will use 
```javascript
<url>?prefer=ultra-low
```
 to test with GNA plugin @Christywl  @mingmingtasd @miaobin

### CODE REVIEW

**Comment by BruceDai** [comment]
Link to  #1125

**Comment by BruceDai** [comment]
@huningxin @fujunwei @ibelem PTAL, thanks.

**Comment by fujunwei** [comment]
LGTM, thanks.

**Comment by BruceDai** [comment]
@ibelem Please help merge this PR, thanks.

**Comment by huningxin** [comment]
Looks good. Thanks @BruceDai !

**Pull request merged**
