### PR TITLE
[Example] Support Tiny Yolo V2 for object detection

### LINKED ISSUE #29: [Sample] Add TinyYOLO based object detection example

### PR DESCRIPTION
**Pull request by Wenzhao-Xiang**
close #29

### CODE REVIEW

**Comment by ibelem** [comment]
Are there any unsupported ops for this demo? Please create relevant issue, we can merge this example after confirming the required ops need to be supported.

**Comment by Wenzhao-Xiang** [comment]
@ibelem @huningxin 
See #494, this example need MAXIMUM op for replace of LEAKY_RELU(MUL + MAXIMUM).
And I see Super Resolution example also need this new op(#475 ).

**Comment by Wenzhao-Xiang** [comment]
Support tiny-yolo-voc for object detection since onnxjs-examples use this model for their objection detection sample.
This model is trained by pascal dataset, and can detection 20 classes object.

**Our:**
image

**Onnxjs:**
image

**Comment by Wenzhao-Xiang** [comment]
@huningxin @ibelem 
I also test the performance between them and us, here is the result:

Backend: GPU (**GTX 1080 TI**)
Browser: **Chrome**, Version 71.0.3578.98 (Official Build) unknown (64-bit)
Tool: Chrome profiler performance tab

**Onnxjs:**

image

About **7~10fps**

**WebNN(Polyfill):**

image

About **20~26fps**

**Comment by Wenzhao-Xiang** [comment]
Updated it to the newest version of UI. @ibelem Please help take a look!

**Comment by ibelem** [comment]
LGTM, thanks @Wenzhao-Xiang's hard work and several @pinzhenx 's improvement suggestions in codes! Great job!

**Pull request merged**
