### PR TITLE
[Example] Update UE when switching dual backends

### LINKED ISSUE #775: [Example] Confused dual backends user experiences
- Add "x" for dual backends, users can click the item again to cancel the selection
- None selected, keep error message in page
- Update title for dual backends and single backend

### PR DESCRIPTION
**Pull request by ibelem**
Fix #775 
- Add "x" for dual backends, users can click the item again to cancel the selection
- None selected, keep error message in page
- Update title for dual backends and single backend

Test URL: https://ibelem.github.io/webml-website/examples/image_classification/?prefer=sustained&b=WASM&m=mobilenet_v1&t=tflite&s=image&d=0 

@pinzhenx @huningxin @Wenzhao-Xiang PTAL

### CODE REVIEW

**Comment by pinzhenx** [comment]
It's much more intuitive and straightforward and looks good to me. Thanks!

**Comment by pinzhenx** [comment]
One small issue: The X mark (U+26CC) cannot show on the mac.

**Comment by ibelem** [comment]
Thanks @pinzhenx for pointing the display issue out, it has been fixed in new commit. PTAL

**Comment by pinzhenx** [comment]
@ibelem Looks good! Thanks

**Pull request merged**
