### PR TITLE
Fix #552 difficult to detect pose issue

### LINKED ISSUE #552: [Example][PoseNet] difficult to detect pose when using live camera view

### PR DESCRIPTION
**Pull request by ibelem**
The initial guiState.scaleFactor value was updated to 0.75 during the testing, which should be set to 0.5 by default.

@huningxin PTAL

### CODE REVIEW

**Comment by huningxin** [comment]
Thanks! I tried the PR, the face landmarks detection works better. However, I still feel the skeleton detection is worse than previous version. Was there any changes for the camera capture part?

**Comment by huningxin** [comment]
> However, I still feel the skeleton detection is worse than previous version

I mean compare to https://brucedai.github.io/nt/examples/posenet/camera.html

**Comment by ibelem** [comment]
@huningxin , the issue should be fixed by adding 

`width ='640' height ='480' `

for `<canvas hidden id='scalevideo' ></canvas>`.

Thanks for reporting the bug! :)

**Comment by huningxin** [comment]
It works well. Thanks!

**Pull request merged**
