### PR TITLE
[Image Classification] UE improvement: Set model = none by default 

### PR DESCRIPTION
**Pull request by ibelem**
[Image Classification] UE improvement: Set model=none by default to reduce unexpected MobileNetV1 loading at first time.

Users may don't need to load MobileNetV1 at all when visit the Image Classification page at first time, give them a choice and avoid 16.9MB model loading.

### CODE REVIEW

**Comment by ibelem** [comment]
@huningxin @pinzhenx @Wenzhao-Xiang please review.

**Comment by pinzhenx** [comment]
Looks good! The experience is getting better. Thanks

**Comment by pinzhenx** [comment]
Could you help us to remove this `0%` label. It will result in dotted lines at the beginning of the progress bar. https://github.com/intel/webml-polyfill/blob/4deae54206da43fc398417eaeaf315db95bc64af/examples/image_classification/index.html#L184
https://github.com/intel/webml-polyfill/blob/4deae54206da43fc398417eaeaf315db95bc64af/examples/image_classification/main.js#L49

**Comment by ibelem** [comment]
Thanks @pinzhenx , please review the updates!

**Comment by pinzhenx** [comment]
@ibelem That's great. Thanks

**Comment by ibelem** [comment]
Thanks for the review! Merge this PR.

**Pull request merged**
