### PR TITLE
[example] Define the threshold value for GNA in particular

### PR DESCRIPTION
**Pull request by mingmingtasd**
@miaobin @fujunwei  Please help to review, thanks!

### CODE REVIEW

**Comment by fujunwei** [comment]
LGTM, thanks.

**Comment by ibelem** [comment]
@mingmingtasd Thanks, could you please add more descriptions about the threshold for GNA value in the conversation for a record? E.g. Why do we need this change.

**Comment by mingmingtasd** [comment]
> @mingmingtasd Thanks, could you please add more descriptions about the threshold for GNA value in the conversation for a record? E.g. Why do we need this change.

 threshold is a limitation to compare with the max error of the actual output to check whether the output is correct. While testing on ICL, we found that: on WebNN (GNA_HW/GNA_SW), **max error < 1**; on WASM and WebGL, **max error < 0.0001**. So we define the threshold value for GNA_HW/GNA_SW in particular.

**Comment by ibelem** [comment]
Thanks @mingmingtasd

**Pull request merged**
