### PR TITLE
[example] Add face recognition use case with facenet(OpenVino) model

### PR DESCRIPTION
**Pull request by cuiyanx**
Signed-off-by: cuiyan <yanx.cui@intel.com>

### CODE REVIEW

**Comment by cuiyanx** [comment]
@BruceDai please review

**Comment by Wenzhao-Xiang** [comment]
@cuiyanx How about providing a converted model? So users can downlowd it derectly.

**Comment by ibelem** [comment]
Thanks for the great contribution @cuiyanx, good job!

I prefer to split the code with 2 PRs. The first one is for src/nn/ code only, and the other one is for example. BTW, do not add face recognition link (the `<a href=""></a>`) in home page and navigation bar before team decide to publish it.

**Comment by cuiyanx** [comment]
@Wenzhao-Xiang OK, point this URL: https://github.com/cuiyanx/webml-polyfill/tree/add-face-recognition-example-with-facenet-openvino/examples/face_recognition/model

@ibelem Yes, this is so clear. I will do.

**Comment by cuiyanx** [comment]
So, close this PR, I will submit 2 PR to replace this.

**Pull request closed without merging**
