### PR TITLE
[test] Update quant8 data for PRELU test cases

### LINKED ISSUE #1061: [test] PRELU can't use a tensor of 8 bit signed integers as the input
For PRELU in NNAPI, the supported tensor OperandCode :

ANEURALNETWORKS_TENSOR_FLOAT16
ANEURALNETWORKS_TENSOR_FLOAT32
ANEURALNETWORKS_TENSOR_QUANT8_ASYMM

Link: https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a82e7e7c709ad117a0178203217be30cf

As I commented here: https://github.com/intel/webml-polyfill/commit/83c8bea14ecb3811f19aab342d2cc9e2bdd71f63#diff-4b7bf8d4f7e00493844449bef72c979fR13.
All the five prelu_quant8 cts cases can not pass on Android platform caused by using a tensor of 8 bit signed integers as the input.

### PR DESCRIPTION
**Pull request by cuiyanx**
fixes #1061 

Signed-off-by: cuiyan <yanx.cui@intel.com>

### CODE REVIEW

**Comment by cuiyanx** [comment]
@mingmingtasd would you help me to test new data? thanks!
@BruceDai please review.

**Comment by mingmingtasd** [comment]
> @mingmingtasd would you help me to test new data? thanks!
> @BruceDai please review.
@cuiyanx OK, no problem. These updated codes looks good this time.

**Comment by BruceDai** [comment]
Thanks @mingmingtasd to report this unsigned issue.
LGTM @cuiyanx 
@ibelem, please help merge this PR, thanks.

**Comment by mingmingtasd** [comment]
I have tested these five quant8 cts cases for PRELU, all pass. Thanks! @BruceDai @cuiyanx

**Pull request merged**
