### PR TITLE
[Polyfill] Refactor building subgraphs

### PR DESCRIPTION
**Pull request by pinzhenx**
No regression found.

**Before**

wasm
passes: 552 failures: 307

webgl
passes: 524 failures: 335

**After**

wasm
passes: 552 failures: 307

webgl
passes: 524 failures: 335

### CODE REVIEW

**Comment by pinzhenx** [comment]
- Separate profiler code
- Remove several hacks in WebGL profiling

**Comment by huningxin** [comment]
@pinzhenx , the PR has conflicts, please help rework on top of tree. Thanks.

**Comment by pinzhenx** [comment]
@huningxin Conflict fixed. PTAL. Thanks

**Comment by huningxin** [comment]
Looks good. Thanks.

**Pull request merged**
