### PR TITLE
[test/tool] Update regression checker tool to support chromium 79

### PR DESCRIPTION
**Pull request by cuiyanx**
Signed-off-by: cuiyanx <yanx.cui@intel.com>

### CODE REVIEW

**Comment by cuiyanx** [comment]
@BruceDai PTAL

**Comment by BruceDai** [comment]
LGTM, thanks @cuiyanx 
@ibelem Please help this PR, thanks.

**Comment by ibelem** [comment]
Thanks @cuiyanx. Question to @cuiyanx, @BruceDai  and @Christywl , shall we update webml-polyfill/blob/master/package.json as well for `chromedriver` and `selenium-webdriver`?

**Comment by BruceDai** [comment]
@ibelem Yes. From Travis CI build details, the used Chrome version is : Chrome/79.0.3945.88, so  we could upgrade chromedriver and selenium-webdriver of webml-polyfill/blob/master/package.json as well, and also need upgrade Circle CI's docker image to align with upgraded chromedriver.

**Comment by ibelem** [comment]
@BruceDai @cuiyanx  will you create a new pr or update in this PR?

**Comment by BruceDai** [comment]
@ibelem I assign @shenx3x to do this upgrade, and his PR would be submitted soon, thanks.

**Pull request merged**
