### PR TITLE
[Example] UI update for Facial Landmark Detection

### PR DESCRIPTION
**Pull request by ibelem**
- Code refactor for Facial Landmark Detection
- Example main page and model page update
- The DAN (TFLite) model was selected by default

@Wenzhao-Xiang @pinzhenx @huningxin PTAL

https://ibelem.github.io/webml-website/examples/

Known: 
- No ops offload feature for this example at present
- This example uses two models, the utils call is splitted, e.g.
```
    landmarkDetector.deleteAll();
    faceDetector.deleteAll();
```
vs 
    `utils.deleteAll();`, and `utils.backend = ''; `was isolated in ui.common.js

### CODE REVIEW

**Comment by ibelem** [comment]
@Wenzhao-Xiang @pinzhenx updated, please check the new commits.

**Comment by Wenzhao-Xiang** [comment]
Do we need display the `DAN(TFlite)` in the title? Because this is the true landmark detection model.

**Comment by pinzhenx** [comment]
I have added support for the hybrid backend. However, after enabling offloaded ops, the "deleteAll" issue came up again.

**Comment by Wenzhao-Xiang** [comment]
LGTM! Thanks @ibelem @pinzhenx for  the great work. Now, this example still have issue on WebNN backend, and I will solve it in another PR.

**Comment by ibelem** [comment]
@Wenzhao-Xiang #691 "[Facial Landmark] Display DAN(TFlite) in title" created.

**Pull request merged**
