### PR TITLE
[Example] Fix some MS Edge compatibility issues

### PR DESCRIPTION
**Pull request by ibelem**
We don't need to fix more for MS Edge except this PR since old version of Edge is not the priority.

Fixed errors for MS Edge (EdgeHTML) and the **WebGL** backend works now: 
- Remove generator code `async * layerIterator(inputTensors, layerList)` in `TFliteModelImporter.js` 
- Add pofyfill for `URLSearchParams` (MIT License)
- SVG Logo display issue

Improved warnings in Edge console:
- Add unmatched end tag in page footer

Won't fix for MS Edge (EdgeHTML):
- **WASM** backend for large models is unable to work 
- Loading animation shows abnormal

Following tests **passed** in MS Edge (EdgeHTML) with **WebGL** backend: 
- Image Classification - TFLite: Mobilenet v1/v2, SqueezeNet, Inception v3/v4, Inception Resnet v2
- Image Classification - ONNX: Mobilenet v1/v2, SqueezeNet, Resnet50 v1, DenseNet
- Object Detection: SSD MobileNet v1/v2, SSDLite MobileNet v2, Tiny Yolo v2 COCO, Tiny Yolo v2 VOC
- Skeleton Detection
- Facial Landmark Detection + DAN (TFlite):  SSD MobileNet v1/v2, SSDLite MobileNet v2, Tiny Yolo v2 

Following tests **passed** in MS Edge (EdgeHTML) with **WASM** backend: 
- Image Classification - TFLite: Mobilenet v1/v2 Quant, SqueezeNet
- Image Classification - ONNX: SqueezeNet
- Object Detection: SSD MobileNet v1/v2 Quant

Following tests **failed** in MS Edge (EdgeHTML) with **WebGL** backend: 
- Image Classification - ONNX: Resnet50 v2, Inception v2
- Semantic Segmentation
- Super Resolution

Tested on:
- MS Edge 4116299.1004.0 / EdgeHTML 16.16299 on Windows 10.0.16299
- ThinkPad T460 / i5-6440HQ / 16GB

@huningxin @Wenzhao-Xiang @pinzhenx PTAL

@BruceDai @Christywl @zhaoming0 please note that, from this commit, please use `TFliteModelImporter_test.js` instead of `TFliteModelImporter.js` in our test frameworks, the `async * layerIterator(inputTensors, layerList)` was removed in `TFliteModelImporter.js` for Edge compatibility.

### CODE REVIEW

**Comment by huningxin** [comment]
Great work! Thanks much @belem ! Looks good to me.

**Comment by Wenzhao-Xiang** [comment]
I tested with my machine yesterday, and found the small model like `Squeeze( tflite/onnx )` and `Mobilenet V1/V2 Quant` work as expect on  WASM backend. Could @ibelem help verify?

**Comment by ibelem** [comment]
Thanks @Wenzhao-Xiang, i am still verifying other use cases, will check your findings. :)

**Comment by ibelem** [comment]
Merge this PR, thanks!

**Pull request merged**
