### PR TITLE
[API][WASM] support TENSOR_QUANT8_ASYMM_SIGNED in AVERAGE_POOL_2D

### LINKED ISSUE #1227: [API] support TENSOR_QUANT8_ASYMM_SIGNED in AVERAGE_POOL_2D

### PR DESCRIPTION
**Pull request by huningxin**
Fix #1227 #1222

### CODE REVIEW

**Comment by huningxin** [comment]
@cuiyanx , please let me know what test cases in #1212 to test this feature. Thanks!

**Comment by cuiyanx** [comment]
@huningxin 
just https://github.com/cuiyanx/dnnl-models/blob/master/select-CTS-test/AVERAGE_POOL_2D/V1_3/avg_pool_quant8_signed.js, not any more.

**Comment by huningxin** [comment]
> @huningxin
> just https://github.com/cuiyanx/dnnl-models/blob/master/select-CTS-test/AVERAGE_POOL_2D/V1_3/avg_pool_quant8_signed.js, not any more.

Thanks @cuiyanx ! I tested this PR against avg_pool_quant8_signed.js, all test cases passed.

Regression test result: passes: 482 failures: 255 (baseline passes: 482 failures: 255), no regression.

@lisa0314 @cuiyanx , please review the API change.

@akineeic , please take a look at the wasm implementation.

**Comment by akineeic** [comment]
@huningxin LGTM, thanks!

**Comment by cuiyanx** [comment]
LGTM, thanks @huningxin

**Comment by lisa0314** [comment]
LGTM, thanks @huningxin

**Comment by huningxin** [comment]
Thanks for the review.

**Pull request merged**
