### PR TITLE
[Example] Add dual/single backends switch

### LINKED ISSUE #775: [Example] Confused dual backends user experiences
- Add "x" for dual backends, users can click the item again to cancel the selection
- None selected, keep error message in page
- Update title for dual backends and single backend

### PR DESCRIPTION
**Pull request by ibelem**
Continue to fix #775 

Now it will support both single backend model and dual backends model selection.

Test URL: https://ibelem.github.io/webml-website/examples/image_classification/ 

@huningxin @pinzhenx @fujunwei @Christywl @Wenzhao-Xiang  PTAL

### CODE REVIEW

**Comment by ibelem** [comment]
Will keep current design and UE, PTAL

**Comment by pinzhenx** [comment]
LGTM. Thanks a lot!

**Comment by Wenzhao-Xiang** [comment]
LGTM! Thanks for the great job!

**Comment by ibelem** [comment]
Thanks, merge this PR.

**Pull request merged**
