### PR TITLE
[nn v2] implement transpose op and fix issue of conv2d

### PR DESCRIPTION
**Pull request by huningxin**
The transpose op is required by LeNet. 

@BruceDai @ibelem , PTAL. Thanks!

### CODE REVIEW

**Comment by BruceDai** [comment]
LGTM, thanks @huningxin

**Comment by huningxin** [comment]
Thanks for reviewing.

**Comment by huningxin** [comment]
@ibelem , thanks for merging. Could you please help publish the new version? So I can write LeNet example in codepen.io to use it. Thanks!

**Comment by BruceDai** [comment]
@huningxin @ibelem I have publish this new version, please use latest

https://intel.github.io/webml-polyfill/dist/tfjs-backend-wasm.wasm
https://intel.github.io/webml-polyfill/dist/webml-polyfill.js
https://intel.github.io/webml-polyfill/dist/webml-polyfill.js.map

Thanks.

**Pull request merged**
