### PR TITLE
Update supported_ops.md

### PR DESCRIPTION
**Pull request by huningxin**
Add FULLY_CONNECTED op and update BNNS column.

### CODE REVIEW

**Comment by huningxin** [comment]
@lisa0314 , please review the BNNS column change
@BruceDai , please review the FULLY_CONNECTED coverage

Thanks!

**Comment by BruceDai** [comment]
@huningxin That's correct, all backend support FULLY_CONNECTED op.

**Comment by huningxin** [comment]
thanks @BruceDai . ping @lisa0314

**Comment by lisa0314** [comment]
@huningxin  reshape is not supported for BNNS backend by now. The other ops are correct.

**Comment by huningxin** [comment]
> reshape is not supported for BNNS backend by now

According to your [implementation](https://github.com/otcshare/chromium-src/blob/webml/services/ml/execution_impl_mac_bnns.mm#L230), you handle the reshape by memory copy, is it correct? If it is, I think this means "supported". What do you think?

**Comment by huningxin** [comment]
Thanks for review!

**Pull request merged**
