### PR TITLE
[WASM] Fixed a build error caused by Emscripten version

### LINKED ISSUE #1004: [WASM] There is a build error with Emscripten (newest version 1.38.46) tool on WASM
There is a build error with Emscripten (newest version 1.38.46) tool on WASM. The [tensorflow](https://github.com/tensorflow/tensorflow/tree/r1.13) version is 1.13.
Error info:
Screenshot from 2019-09-29 16-16-32

### PR DESCRIPTION
**Pull request by akineeic**
Closes #1004

### CODE REVIEW

**Comment by huningxin** [comment]
Thanks @akineeic . Please link this PR to the issue by [fix](https://help.github.com/en/articles/closing-issues-using-keywords).

Couple of questions:
1. do you know the root cause of this issue?
2. does this patch work for previous emscripten version?

**Comment by akineeic** [comment]
> Thanks @akineeic . Please link this PR to the issue by [fix](https://help.github.com/en/articles/closing-issues-using-keywords).
> 
> Couple of questions:
> 
> 1. do you know the root cause of this issue?
> 2. does this patch work for previous emscripten version?

I'm still working on figuring out the cause. I have tested the version 1.38.40 yesterday and it works on that version, the earlier version can be tested if needed.

**Comment by huningxin** [comment]
@akineeic , any updates on this PR?

**Comment by akineeic** [comment]
> @akineeic , any updates on this PR?

It seems like that the newest version of emscripten doesn't support the writing format of the RuntimeShape's overloading constructor function, but I haven't find the correct way to write it yet.

**Comment by akineeic** [comment]
I have tested the binding class RuntimeShape in the console, both way to overload the constructor only expose [one constructor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/types.h#L139-L147) with one parameter in type of int. In this PR, the emscripten version 1.38.30 is still able to build nn_ops.js and the example using the binding class RuntimeShape is still able to run.

**Comment by huningxin** [comment]
Thanks for the investigation. As it works for both emscripten, let's merge it while waiting for upstream's response on https://github.com/emscripten-core/emscripten/issues/9704.

**Pull request merged**
