### PR TITLE
[Example] UI Enhancement of DeepLab

### LINKED ISSUE #600: [DeepLab] UI enhancements
- Fix initial display size
- Label computation bug

### PR DESCRIPTION
**Pull request by pinzhenx**
Fix #600

### CODE REVIEW

**Comment by pinzhenx** [comment]
- Fix canvas size to 513
- Fix label computation bug

**Comment by ibelem** [comment]
@pinzhenx please fix the conflict due to the merged ui.js refactor pr.

**Comment by pinzhenx** [comment]
@ibelem Conflict fixed. PTAL, Thanks!

**Comment by ibelem** [comment]
Great job, tried the demo and the label computation issue is gone. Thanks!

**Pull request merged**
