### PR TITLE
[test] Update cts test cases and unit test cases

### PR DESCRIPTION
**Pull request by cuiyanx**
1. Update cts test cases and all-test file.
2. Remove some `V1_0_plus` test cases to `test_supplement`.
3. Change some 'const' to 'let' for test_supplement test case.
4. Update unit test cases.

Signed-off-by: cuiyanx <yanx.cui@intel.com>

### CODE REVIEW

**Comment by cuiyanx** [comment]
@BruceDai PTAL

**Comment by BruceDai** [comment]
Hi @ibelem 
This PR and PR #1120 are being updated by @cuiyanx according to our local test feedback.
Being waiting for next commit.

**Comment by cuiyanx** [comment]
I skip some test cases that are not supported and delete some test cases that are blocked by chrome because too big data like [5, 50, 63, 3].

@BruceDai PTAL

**Comment by BruceDai** [comment]
LGTM, thanks @cuiyanx 
@ibelem We verified those changed test cases, please help merge this PR, thanks

**Pull request merged**
