### PR TITLE
[WebGL2] Revise InputLayer to fix memory leak

### PR DESCRIPTION
**Pull request by GreyZzzzzzXh**
This memory leak caused the benchmark to crash and be inaccurate.

### CODE REVIEW

**Comment by GreyZzzzzzXh** [comment]
@Wenzhao-Xiang, please help take a look, thanks!

**Comment by huningxin** [comment]
@GreyZzzzzzXh , thanks for the PR! Could you please work with @BruceDai to run the submission test for WebGL backend?

@Wenzhao-Xiang , please help review the code.

**Comment by Wenzhao-Xiang** [comment]
@huningxin , look good to me!

**Comment by huningxin** [comment]
@GreyZzzzzzXh , Could you please explain the root cause of memory leak and your solution? That will be good document for other contributors.

**Comment by huningxin** [comment]
Merge it first and complete the doc later.

**Comment by GreyZzzzzzXh** [comment]
Each time we call this function `Input.call()`, some **webgl textures** are created by
 `this.inputTensor.createGLTexture({ type: '2d', format: 'float', supportSliceTexture: true });`
(`gl.createTexture()` is called in `Tensor.createGLTexture()`, and created texture can only be deleted by `gl.deleteTexture(texture)`).

This leads to an increase in memory usage after `Input.call()` is used several times, so a better way is to create textures in warm-up stage and replace the data in inference stage.

Besides, considering there are multiple input models, e.g. [examples/simple](https://github.com/intel/webml-polyfill/tree/master/examples/simple), i modify the input layer to generate multiple tensors per call.

**Pull request merged**
