### PR TITLE
[tool] Added workload automation test toolkit for Linux and Windows platforms.

### PR DESCRIPTION
**Pull request by BruceDai**
@huningxin @ibelem PTAL, thanks.

### CODE REVIEW

**Comment by ibelem** [comment]
Thanks @BruceDai. Will @miaobin's build system integrate this automation tool, when new builds are generated, perform the testing automatically?

**Comment by BruceDai** [comment]
@ibelem We can use Crontab command on Linux and Task Scheduler tool on Windows to create workload test task using latest released nightly build on test devices，thanks.

**Comment by ibelem** [comment]
My concern is it still shows no regression even there is 10% performance drop, we'd better to add the threshold for developers, 10% is enough to attract everyone's attention.

**Comment by BruceDai** [comment]
@ibelem I've submitted new patch to improve regression check with regression criterion of 10% performance downgrade, please take another look, thanks.

**Comment by ibelem** [comment]
LGTM, thanks

**Pull request merged**
