### PR TITLE
[example] Create a new execution for each prediction to fix #1060 Android bug

### LINKED ISSUE #1060: [NNAPI] The prediction results of use cases on Android version 10.0  are incorrect
Test Env:
Chromium Version:  nightly build 79.0.3917.0 (e7b9a67)
Platform: Android 10; Pixel 2 XL

Expected Result:
The prediction results should be correct on Android version 10.0.

Actual Result:
The prediction results of use cases on Android version 10.0 are incorrect everytime after selecting a new model and then selecting the WebNN backend. But if we click the WebNN backend again, the prediction results will be updated correctly. I choose image classification and semantic segmentation as examples:

Screenshot from 2019-11-06 09-46-21
Screenshot from 2019-11-06 09-46-33
Screenshot from 2019-11-06 09-45-32
Screenshot from 2019-11-06 09-45-48

How to Reproduce:

1. Install the chromium apk on the Android phone with version 10.0.

2. Start local server using "npm start", and visit “http://<192.168.42.*>:8080/examples/image_classification" or "http://<192.168.42.*>:8080/examples/semantic_segmentation" on chromium.

3. Select one model and select "SUSTAINED_SPEED" as backend, you'll get wrong prediction results.

4. Click the "SUSTAINED_SPEED" again and then the prediction results will be right.

### PR DESCRIPTION
**Pull request by mingmingtasd**
I have verified these examples, now they can run successfully on Android 10 (Pixel 2 XL). Please help to review. Thanks! @BruceDai

### CODE REVIEW

**Comment by pinzhenx** [comment]
Hi @BruceDai 

The semantics of compilation time will be changed by this commit.
https://github.com/intel/webml-polyfill/pull/423#issuecomment-452553368

**Comment by mingmingtasd** [comment]
> Hi @BruceDai
> 
> The semantics of compilation time will be changed by this commit.
> [#423 (comment)](https://github.com/intel/webml-polyfill/pull/423#issuecomment-452553368)
> 
> We may also need to verify if there's any performance drop due to recreation of the `execution`.

Good reminder. And the inference time printed out will increase as the compilation time decrease, is that right? @pinzhenx @BruceDai

**Comment by fujunwei** [comment]
Does WebNN API need to align with Android NNAPI [seeing below section](https://developer.android.com/ndk/reference/group/neural-networks#aneuralnetworksexecution)

`An execution can be applied to a model with ANeuralNetworksExecution_burstCompute, ANeuralNetworksExecution_compute or ANeuralNetworksExecution_startCompute only once. Create new executions to do new evaluations of the model.`

Or WebNN API can reuse execution and adjust implementation in Android NNAPI backend.

**Comment by ibelem** [comment]
@mingmingtasd Please fix this issue on implementation side rather than polyfill/example utils.

**Pull request closed without merging**
