### PR TITLE
[WebGL] support RESIZE_BILINEAR op

### PR DESCRIPTION
**Pull request by pinzhenx**
Fix https://github.com/intel/webml-polyfill/issues/337

### CODE REVIEW

**Comment by huningxin** [comment]
Thanks @pinzhenx . LGTM. @GreyZzzzzzXh , please take a look as well.

**Comment by huningxin** [comment]
It looks like all the CI fails. @pinzhenx , could you please take a look?

**Comment by BruceDai** [comment]
@huningxin We have caught the root cause for CI failure, and fixed it by update test case for CI. I have rerun build for Travis CI, the result is pass. Since AppVeyor doesn't have 'restart build' function, please refer the result by Travis CI and merge this PR. Thanks.

**Comment by GreyZzzzzzXh** [comment]
LGTM, thanks!

**Comment by huningxin** [comment]
Thanks for the review @GreyZzzzzzXh . Thanks for the CI fixing @BruceDai !

**Pull request merged**
