### PR TITLE
[Example]support example "image_classification_tflite" 

### LINKED ISSUE #220: [Example] support more TFLite image classification models
The existing example (https://github.com/intel/webml-polyfill/tree/master/examples/mobilenet) only supports TFLite MobileNet model for image classification. This task is to make the example more general to support more TFLite image classification models hosted here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md#image-classification-float-models

It requires:
1. refactor the example to load, compile and execute multiple models
2. identify the unsupported ops if the model is not supported

### PR DESCRIPTION
**Pull request by Wenzhao-Xiang**
Fix #220

### CODE REVIEW

**Comment by Wenzhao-Xiang** [comment]
@GreyZzzzzzXh  PTAL, thanks!

**Comment by huningxin** [comment]
@Wenzhao-Xiang , it's great!

I am curious about the memory consumption when loading multiple models. 

Did you have memory consumption data for your example? And did you happen to test on the mobile devices? Thanks.

**Comment by Wenzhao-Xiang** [comment]
@huningxin Thanks for reminding! I test it on mobile phone, and it seems be memory out after several changes of models. I have added garbage reclaiming mechanism with Webgl2 and WASM backend, and it looks ok now. And what's the memory consumption data you mentioned? I'm not sure how to get the data.

**Comment by Wenzhao-Xiang** [comment]
I found the memory of webgl2 and WASM are also not be released when changing backend. When choosing model "inception_v3" and switching the backend for several times, memory errors happened.
Here is the memory consumption data:

**(Each changing time means backend changing from WASM to WebGL2 and then changing back to WASM)**

changing times | app process | GPU process
-- | -- | --
1 | 541623K | 449120K
2 | 692352K | 802003K
3 | 844244K | 1148098K
4 | 993304K | 1494325K
5 | 1144468K | 1839718K

After adding release memory operation for each time when changing backend, it looks better now:

changing times | app process | GPU process
-- | -- | --
1 | 358696K | 436631K
2 | 740372K | 439634K
3 | 357040K | 424109K
4 | 356836K | 425358K
5 | 357040K | 426065K

 Now, the memory will be released when changing model or changing backend. 
Here is the memory consumption data:

**(Each changing time means switching four model, and in each model switching backend from WASM to WebGL2 and then back to WASM)**

changing times | app process | GPU process
-- | -- | --
1 | 289424K | 154891K
2 | 298300K | 124150K
3 | 307996K | 152909K
4 | 317516K | 154288K
5 | 327820K | 115118K

@huningxin @ibelem Please help take a look at the data. And I'll update the PR after unifying the utils interface with @pinzhenx

**Comment by ibelem** [comment]
Will the memory increase when running multiple images or multiple models with same WASM/WebGL2 backend (no backend change)?

**Comment by Wenzhao-Xiang** [comment]
@ibelem  Seems OK to Merge. Thanks!

**Comment by ibelem** [comment]
Thanks for the memory consumption data, very impressive with your memory release relevant codes, it will also help our benchmarks and aimark service with better performance. :)

**Pull request merged**
