### PR TITLE
[Example] Fix onnx bugs on Android

### LINKED ISSUE #349: [NNAPI] Squeezenet(onnx) doesn't work on Android WebML
**Test Env:**
Chromium Version: nightly build 70.0.3503.0 (**9012a59**)
Platform: Android 8.1.0(Google Pixel 2)

**Expected Result:**
Squeezenet(Onnx) example works on WebML.

**Actual Result:**
Squeezenet(Onnx) example doesn't work on WebML. 
`Failed to setup WebML backend`

**How to Reproduce:**
1. Launch chromium on Android device and visit https://brucedai.github.io/nt/examples/image_classification/index.html
2. Select Squeezenet(Onnx)

### PR DESCRIPTION
**Pull request by pinzhenx**
Fix #349, #430, #431, #432, #433, #465

### CODE REVIEW

**Comment by huningxin** [comment]
Thanks @pinzhenx ! Could you please explain the root cause of this issue? Why is it Android specific?

**Comment by pinzhenx** [comment]
Two main reasons cause these issues:

- NNAPI doesn't allow an unused operand
Sometimes we will skip a node and leave some unused operands in the graph. However, NNAPI will not optimize out them and will report `Operand XXX with lifetime TEMPORARY_VARIABLE is not being written to.`

- Multiple calls to `setOperand` do not overwrite the old value
The default behavior of NNAPI is different from what we implemented on other platforms. In some ONNX models, `Reshape` will have the shape like [0, -1], and the importer will overwrite it with computed shape [1, 1000]. But from debug log, NNAPI still had the value [0, -1], so it failed with `NN_CHECK failed:  numInputElements == numOutputElements`

**Comment by huningxin** [comment]
Nice information, thanks! PR looks good to me.

**Comment by pinzhenx** [comment]
Fix #348

**Pull request merged**
