### PR TITLE
[Example] Prefetch video frames

### PR DESCRIPTION
**Pull request by pinzhenx**

### CODE REVIEW

**Comment by pinzhenx** [comment]
This feature is subject to further testing. Its purpose is to increase the throughput (FPS) on some small models (ssd, squeezenet, etc.) by prefetching video frames asynchronously when using WebNN. So this PR only enabled the feature in object detection and image classification for now. And I could see the FPS of ssd quant. on Android go from 29 FPS to 38 FPS.

**Comment by pinzhenx** [comment]
BTW, this PR also fixed a performance issue in the preprocessing of image classification. So if we want to fairly compare this feature, we cannot use the classification example. For instance, the FPS of the squeezenet on mkldnn goes from 35 to 48, but it can't all be attributed to the prefetching.

**Comment by huningxin** [comment]
I understand the main idea of this PR intends to let the JS thread busy for preprocessing while WebNN is computing. Correct?

**Comment by pinzhenx** [comment]
@huningxin Yes. So it will not improve the throughput when using the polyfill backend.

**Pull request closed without merging**
