### PR TITLE
[Example] code refactor for image classification

### LINKED ISSUE #399: [Example] Specify subtest in the URL directly for image classification test
[Customer] An issue I have when automating execution and testing of these tests is that if WebML context can be created, the test fall backs to WebGL for example, and I have to do additional checks to verify if the test ran with the API I expected, otherwise I get false results. 

I see you are doing URL parsing already, would it be possible to add a feature for forcing the API? Something like https://huningxin.github.io/webml-examples/examples/ssd_mobilenet?force_api=WebGL2, and if WebGL2 context can’t be created, rather than falling back to WASM, the test fails instead? 

Also it would be great if it was possible to specify the subtest in the URL directly for image classification test, so something like: https://huningxin.github.io/webml-examples/examples/image_classification/index.html?force_api=WebGL2&force_test=SqueezeNet(Onnx) works.

### LINKED ISSUE #422: [Example] Code refactor for Image Classfication
- UI change
- promise to async/await in main.js
- url enhancement for #399 
- Will not add service worker for the example

### PR DESCRIPTION
**Pull request by ibelem**
Fix #422 
- ui optimization 
- url improvements, fix #399 
- global navigation 
- dropdownlist improvement 
- mobile/tablet responsive 
- fix header display issue on small screen devices etc.

Please visit [image_classification/README.md](https://github.com/intel/webml-polyfill/blob/master/examples/image_classification/README.md) for more details.

### CODE REVIEW

**Comment by ibelem** [comment]
@huningxin @Wenzhao-Xiang @pinzhenx please review.

**Comment by ibelem** [comment]
@huningxin @Wenzhao-Xiang @pinzhenx please review the latest version with seperated loadModel from init by @pinzhenx's. If no problem, please merge the code.

**Comment by Wenzhao-Xiang** [comment]
@ibelem  
Thanks for the great job! It looks good to me!

I also test the new example in Android platform with WASM (Pixel2, chrome 71), and unexpected to found all the image classification models passed(The old one can't pass ResnetV2(Onnx) #441 )! It's really  a good improvement!
Seems Javascript memory will effects WASM memory allocating?
I will investigate it then.

**Comment by huningxin** [comment]
Great job done! Thanks @ibelem @Wenzhao-Xiang @pinzhenx for the coding and review!

**Pull request merged**
