### PR TITLE
[WASM] Fix the memory issue of tfjs-wasm-backend.

### LINKED ISSUE #1258: [WASM] memory issue occurs for WASM(TF.js) backend
**Test Env:**
webml-polyfill commit: https://github.com/intel/webml-polyfill/commit/a58f9f5340ca87eca4cda18db019f42752317f9e
Platforms: all

**Expected Result:**
No memory issue.

**Actual Result:**
memory issue occurs for WASM(TF.js) backend:
wasm-1
wasm-2

**_Notes: In this case, all models can't be ran, need restart Chromium to continue the testing when meeting this issue._**

**How to Reproduce:**
1. Setup server with commit https://github.com/intel/webml-polyfill/commit/a58f9f5340ca87eca4cda18db019f42752317f9e
2. launch chrome or chromium(disable webml)
3. Visit http://localhost:8080/examples/image_classification
4. Switch models between ResNet50 v1(ONNX) and ResNet50 v2(ONNX) for several times (larger models usually meet this issue)

### PR DESCRIPTION
**Pull request by akineeic**
Fixed #1258

### CODE REVIEW

**Comment by BruceDai** [comment]
@akineeic Thanks for fixing this memory issue. LGTM.

**Comment by akineeic** [comment]
This issue occurs because the memory of wasm module wasn't released when change the model.
I have tested with @Christywl with no error. @BruceDai @huningxin  PTAL, thanks!

**Comment by BruceDai** [comment]
@ibelem Please help merge this PR, thanks.

**Comment by ibelem** [comment]
Do you mean the memory issue is not related to wasm backend side but the example side? @BruceDai @akineeic

**Comment by akineeic** [comment]
> Do you mean the memory issue is not related to wasm backend side but the example side? @BruceDai @akineeic

We need to release variables in wasm module manually. @BruceDai has implemented the related function already, but we just forgot to call it in the case of changing model.

**Pull request merged**
