### PR TITLE
Aviod recompile model for Object Detection and Semantic Segmentation

### LINKED ISSUE #598: [Example] avoid recompile model when switch image and camera views
It seems to me switching image and camera views would cause model recompilation. If it is the case, we should avoid that.

@ibelem

### PR DESCRIPTION
**Pull request by ibelem**
@pinzhenx @Wenzhao-Xiang PTAL, thanks!

Fix #598

### CODE REVIEW

**Comment by pinzhenx** [comment]
LGTM. I appreciate it.

**Comment by ibelem** [comment]
@Wenzhao-Xiang PTAL for the canvas size issue.

**Comment by ibelem** [comment]
@Wenzhao-Xiang The image extends to right when width <=768px issue has been fixed, PTAL

**Comment by Wenzhao-Xiang** [comment]
LGTM! Thanks!

**Comment by ibelem** [comment]
Thanks a lot @pinzhenx @Wenzhao-Xiang !

**Pull request merged**
