### PR TITLE
[test] Reset timeout to run CTS test cases for CTS tool

### PR DESCRIPTION
**Pull request by cuiyanx**
Signed-off-by: cuiyan <yanx.cui@intel.com>

### CODE REVIEW

**Comment by cuiyanx** [comment]
@BruceDai please review

**Comment by BruceDai** [comment]
Currently, it's OK to set 20s timeout.
LGTM, thanks @cuiyanx 
@ibelem, PTAL, thanks

**Comment by ibelem** [comment]
Any reason to add the timeout? it's better to add some background and description.

**Comment by cuiyanx** [comment]
@ibelem Recently, some CTS test cases have be failed because timeout error. The default timeout time of mocha is 2000 ms that not enough to run CTS test case. So we must increase the timeout time to run CTS test case completely.

**Comment by ibelem** [comment]
Thanks! LGTM.

**Pull request merged**
