### PR TITLE
[Example] Remove dat.gui.js in Posenet to save 87KB

### PR DESCRIPTION
**Pull request by ibelem**
Finally I started this task, the dat.gui.js has been removed in Posenet.

1. Save file (dat.gui.js) size when fetching files from server
2. Avoid further IP scan issue for marking dat.gui.js 

@Wenzhao-Xiang @pinzhenx PTAL

@Christywl @BruceDai please be noted.

### CODE REVIEW

**Comment by pinzhenx** [comment]
https://github.com/intel/webml-polyfill/blob/117917dbd51b58b03d7f5d06cf51d3fe800e0f90/examples/skeleton_detection/ui.js#L141

https://github.com/intel/webml-polyfill/blob/117917dbd51b58b03d7f5d06cf51d3fe800e0f90/examples/skeleton_detection/ui.js#L184

Thanks for the PR. These two lines need to be deleted.

**Comment by ibelem** [comment]
@pinzhenx Weird, i should search all but didn't do it this time, fixed in https://github.com/intel/webml-polyfill/pull/883/commits/f0d6527e3e0e9f792a065343bcddc68edf0ecc85 , thanks!

**Comment by pinzhenx** [comment]
LGTM. Thanks!

**Comment by ibelem** [comment]
Thanks! Merge this PR.

**Pull request merged**
