### PR TITLE
[WASM/WebGL] Fixed some issues of boundary value.

### PR DESCRIPTION
**Pull request by BruceDai**
This PR is to: 
1. Fixed some issues of boundary value.             
2. Removed some invalid default codes of switch blocks since those exceptions are checked to throw error before.

@Wenzhao-Xiang @GreyZzzzzzXh Please help review those modifications, thanks.

### CODE REVIEW

**Comment by Wenzhao-Xiang** [comment]
LGTM, thanks!

**Comment by GreyZzzzzzXh** [comment]
LGTM, thanks!

**Comment by huningxin** [comment]
Thanks!

**Comment by GreyZzzzzzXh** [comment]
Hi @BruceDai ,

I found these default code still make sense. For example, in present super-resolution demo (hosted on https://greyzzzzzzxh.github.io/webml-examples/examples/super_resolution/index.html), when switching backend from WebGL to WASM (transpose and batchToSpaceND are still not supported in wasm), there will be no any error, and we will get an incorrect result. 

31CF2FSKTX}SEOVCDG1Y5U1 

I commit these code in PR #475 https://github.com/intel/webml-polyfill/pull/475/commits/50732f21cd601f5d70feb9fa20e48ad5c85aab02, please take a look.

**Comment by BruceDai** [comment]
@GreyZzzzzzXh Yes, you're right, the default code is to be  invalid when the type is not in these Operation types defined in [API Documentation](https://github.com/intel/webml-polyfill/blob/master/docs/api.md), while for your scenario, the default code should be kept. Thanks.

**Pull request merged**
