### PR TITLE
Support 'Normalize' ops and Int32 data type

### PR DESCRIPTION
**Pull request by cuiyanx**
This PR is face recognition for webnn code part on webgl backend:
1. Implement Int32 data type.
2. Support 'Normalize' ops.

Signed-off-by: cuiyan <yanx.cui@intel.com>

### CODE REVIEW

**Comment by cuiyanx** [comment]
@belem @Wenzhao-Xiang please review

**Comment by ibelem** [comment]
It's better to add some description of your PR.

**Comment by ibelem** [comment]
@BruceDai @huningxin PTAL

**Comment by ibelem** [comment]
Close this PR as @cuiyanx will refactor the code.

**Pull request closed without merging**
