### PR TITLE
[example] Fixed FPS regression issue.

### PR DESCRIPTION
**Pull request by BruceDai**
This PR fixed FPS regression issue #1197, and also modified class name by updating first character of class name to capital letter.
@ibelem PTAL, and go ahead to update #1196, thanks.

### CODE REVIEW

**Comment by huningxin** [comment]
Thanks @BruceDai . It looks like you've done two tasks in one commit. Could you please separate them into  two commits?

**Comment by huningxin** [comment]
> It looks like you've done two tasks in one commit. Could you please separate them into two commits?

I mean you've done renaming and fix FPS issue in one commit. It would be better to put them into two individual commits. Does that make sense?

**Comment by BruceDai** [comment]
Thanks @huningxin.
OK, I will separate into two commits.

**Comment by BruceDai** [comment]
@huningxin Done to separate commit,  PTAL, thanks.

**Comment by huningxin** [comment]
Thanks for separating the commits. Regarding to fixing #1197, could you please document the root cause of that issue? So people can understand your fix. And if you can share the performance data before and after your fix, that would be very helpful.

**Comment by BruceDai** [comment]
@huningxin Please review [this comment](https://github.com/intel/webml-polyfill/issues/1197#issuecomment-611930828) with root cause and performance data for issue #1197, thanks.

**Comment by huningxin** [comment]
Looks good. Thanks for your efforts!

**Comment by huningxin** [comment]
Ping @ibelem .

**Comment by ibelem** [comment]
Thanks @BruceDai for the fix and thanks @huningxin for the review.

**Pull request merged**
